snd-soc-omap-aess-objs := omap-aess-core.o \
			omap-aess-dbg.o \
			omap-aess-fw.o \
			omap-aess-pcm.o \
			omap-aess-opp.o \
			omap-aess-dai.o \
			abe_asrc.o \
			abe_core.o \
			abe_ini.o \
			abe_gain.o \
			abe_port.o \
			port_mgr.o \

obj-$(CONFIG_SND_OMAP_SOC_AESS) += snd-soc-omap-aess.o
